language: ruby
rvm:
- 2.5.0
env:
  global:
  - CC_TEST_REPORTER_ID=85ca9dd8683abc577230481be6e37304a287904bd1897db53b2715984a1bdd66
services:
  - postgresql
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: heroku
  app: acebook-zuckerman
  on:
    repo: EManifold/acebook-zuckermen
  api_key:
    secure: ubvXRjZj9EIU9ep8FzGDlUvHu5aeVmyY1dIoliPFQyK2eNxSXxfF0xL9gG+0JXgZ7IN5GohxI+5dQ0f4xAEAo1oqG/sKnfQPP+m2zVd70rBRwUQQi9tQkXDToWSqylYDqJX36elr0IAJ0Y+ifuSntH73YA5sZfGo+fgS8k2s/OlsVZx6ehIaSZTkWYMcGcBwhzkaue2aKdRu93qmDL3vWchzsyuKOT18Kd5c4fFnN50nXyslG7U+82YEjSjarSDZTtH5oCEQWhfs04nz7GgUJPcX3oPvAPyqWqgzTwfGyQLp4WAxPdkc6BO65yKHGvUIp7Y6zX/y0zcihcKveEcWCJKKN5yaBjaUcC6xFc6gioSO1m0RKdwmF4veCqjv3Wo3ByHZtUYZTpWeIHVxOqPZAfouGKGBuwHXO3Tx+ePxmIsurToPPSGi2IwdbWPyzRJQzvBrQ/6V7KVnd8nITkyhxx1fuV43A0CXPCriOYsqJihsqyseiKzYZEKF4fNZ6pvgn+2041vtj+5Ys7Y55YKD3SXY8aWcsd01//5lfpm6jtkInUhBMZ+/iGx+wyhUmgclJtNscVcqxicAYl22BY+I639olmh8AdI5xG+rtF2KPfrCGRDhj7ki+aFdbMp9SNa/ve8vs1hLiSfs5k0C0OItAhSoaXipm374RI67vq/mUYE=
