language: ruby
rvm:
  - 2.5.0

env:
  - RACK_ENV='test'

before_install:
  - gem install -v 1.17.3 bundler --no-rdoc --no-ri

script:
  - bundle install
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rake db:migrate
  - bundle exec rspec
